//
// Generated file, do not edit! Created by nedtool 4.6 from src/node/application/simpleAggregation/DeadlinePacket.msg.
//

#ifndef _DEADLINEPACKET_M_H_
#define _DEADLINEPACKET_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "ApplicationPacket_m.h"
// }}

/**
 * Class generated from <tt>src/node/application/simpleAggregation/DeadlinePacket.msg:28</tt> by nedtool.
 * <pre>
 * packet DeadlinePacket extends ApplicationPacket
 * {
 *     int64_t deadline;
 * }
 * </pre>
 */
class DeadlinePacket : public ::ApplicationPacket
{
  protected:
    int64_t deadline_var;

  private:
    void copy(const DeadlinePacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const DeadlinePacket&);

  public:
    DeadlinePacket(const char *name=NULL, int kind=0);
    DeadlinePacket(const DeadlinePacket& other);
    virtual ~DeadlinePacket();
    DeadlinePacket& operator=(const DeadlinePacket& other);
    virtual DeadlinePacket *dup() const {return new DeadlinePacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int64_t getDeadline() const;
    virtual void setDeadline(int64_t deadline);
};

inline void doPacking(cCommBuffer *b, DeadlinePacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, DeadlinePacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef _DEADLINEPACKET_M_H_

