//
// Generated file, do not edit! Created by nedtool 4.6 from src/node/communication/routing/simpleRouting/SimpleRoutingPacket.msg.
//

#ifndef _SIMPLEROUTINGPACKET_M_H_
#define _SIMPLEROUTINGPACKET_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "RoutingPacket_m.h"
// }}

/**
 * Enum generated from <tt>src/node/communication/routing/simpleRouting/SimpleRoutingPacket.msg:19</tt> by nedtool.
 * <pre>
 * enum SimpleRoutingPacket_type
 * {
 * 
 *     SIMPLE_ROUTING_DATA_PACKET = 1;
 *     SIMPLE_ROUTING_HOPCOUNT_PACKET = 2;
 * }
 * </pre>
 */
enum SimpleRoutingPacket_type {
    SIMPLE_ROUTING_DATA_PACKET = 1,
    SIMPLE_ROUTING_HOPCOUNT_PACKET = 2
};

/**
 * Class generated from <tt>src/node/communication/routing/simpleRouting/SimpleRoutingPacket.msg:24</tt> by nedtool.
 * <pre>
 * packet SimpleRoutingPacket extends RoutingPacket
 * {
 *     int SimpleRoutingKind @enum(SimpleRoutingPacket_type);
 * 
 *     string source;
 *     string destination;
 * 
 *     int hopcount;
 *     unsigned int packetId;
 * 
 * }
 * </pre>
 */
class SimpleRoutingPacket : public ::RoutingPacket
{
  protected:
    int SimpleRoutingKind_var;
    opp_string source_var;
    opp_string destination_var;
    int hopcount_var;
    unsigned int packetId_var;

  private:
    void copy(const SimpleRoutingPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const SimpleRoutingPacket&);

  public:
    SimpleRoutingPacket(const char *name=NULL, int kind=0);
    SimpleRoutingPacket(const SimpleRoutingPacket& other);
    virtual ~SimpleRoutingPacket();
    SimpleRoutingPacket& operator=(const SimpleRoutingPacket& other);
    virtual SimpleRoutingPacket *dup() const {return new SimpleRoutingPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getSimpleRoutingKind() const;
    virtual void setSimpleRoutingKind(int SimpleRoutingKind);
    virtual const char * getSource() const;
    virtual void setSource(const char * source);
    virtual const char * getDestination() const;
    virtual void setDestination(const char * destination);
    virtual int getHopcount() const;
    virtual void setHopcount(int hopcount);
    virtual unsigned int getPacketId() const;
    virtual void setPacketId(unsigned int packetId);
};

inline void doPacking(cCommBuffer *b, SimpleRoutingPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, SimpleRoutingPacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef _SIMPLEROUTINGPACKET_M_H_

