//
// Generated file, do not edit! Created by nedtool 4.6 from src/node/communication/routing/simpleRouting/SimpleRoutingPacket.msg.
//

#ifndef _SIMPLEROUTINGPACKET_M_H_
#define _SIMPLEROUTINGPACKET_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "OMacRoutingPacket_m.h"
// }}

/**
 * Class generated from <tt>src/node/communication/routing/simpleRouting/SimpleRoutingPacket.msg:19</tt> by nedtool.
 * <pre>
 * packet SimpleRoutingPacket extends OMacRoutingPacket
 * {
 *     int hopcount;
 * }
 * </pre>
 */
class SimpleRoutingPacket : public ::OMacRoutingPacket
{
  protected:
    int hopcount_var;

  private:
    void copy(const SimpleRoutingPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const SimpleRoutingPacket&);

  public:
    SimpleRoutingPacket(const char *name=NULL, int kind=0);
    SimpleRoutingPacket(const SimpleRoutingPacket& other);
    virtual ~SimpleRoutingPacket();
    SimpleRoutingPacket& operator=(const SimpleRoutingPacket& other);
    virtual SimpleRoutingPacket *dup() const {return new SimpleRoutingPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getHopcount() const;
    virtual void setHopcount(int hopcount);
};

inline void doPacking(cCommBuffer *b, SimpleRoutingPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, SimpleRoutingPacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef _SIMPLEROUTINGPACKET_M_H_

